### ISSUE TITLE
Embedding encoded GeoJSON in another JSON object

### ISSUE THREAD

**Issue by alkamin** [bryanjos/geo#24]
I am forming a response as such:

```
  %{
      id: park.id,
      name: park.name,
      geojson: Geo.JSON.encode(park.geom)
    }
```

The resulting response has the GeoJSON object wrapped in double quotes, which causes all the double quotes within the object to be escaped, since the whole thing is being re-encoded by Poison on the way out.  I did a quick test and added an additional function to `geo_json.ex`:

```
def shallow_encode(geom) do
    do_encode(geom)
    |> add_crs(geom.srid)
end
```

which solved the problem.

Instead of the hack, what would be the recommended way to do this?

**Comment by bryanjos** [comment]
I ran into similar issues recently actually and I did some not so nice things too. There should be a change here to account for it.

I think there could be a couple of ways to handle this:

  Option 1. Remove the json encoding altogether, remove the dependency on Poison and users of geo would have to bring their own json parser. I like this because it makes it so someone could use whatever json library they want from that point on.

Option 2. Add some kind of option to the encode function to prevent json encoding. This one is nice because the api only changes if you need more control.

What do you think?

**Comment by alkamin** [comment]
I think the option to bypass the json encoding may be the easiest all around, but option 1 seems like the 'right' way as it also eliminates a dependency.

**Comment by bryanjos** [comment]
Yeah I'm leaning that way too. I'll try to put something together between today and tomorrow

**Comment by bryanjos** [comment]
@alkamin Removing the json encoding got a bit messy, so I went for option 2. Before 1.0 I may go for option 1 though. If it looks ok, I can merge it and publish it later today

**Comment by alkamin** [comment]
It looks good to me, thanks for quickly addressing this!

**Comment by bryanjos** [comment]
No problem. I just updated the version in Hex. 0.15.2
