### ISSUE TITLE
Geo.JSON does not support PointZ

### ISSUE THREAD

**Issue by dongli** [bryanjos/geo#90]
First of all, thanks for such great library! I am using it to store spherical coordinates with height, but I found that `Geo.JSON.encode` does not support PointZ. I am new to Elixir and Phoenix, so any suggestion is welcome! I can separate height from longitude and latitude, but that looks not clean since height is part of a coordinate.

**Comment by bryanjos** [comment]
Hi! You are correct in it's not supported, but only because I don't know how it should be displayed. I remember looking at the GeoJSON spec and not getting any clues. I'm open to suggestions

**Comment by FlorianGerhardt** [comment]
Hey @dongli, this was implemented in geo 3.1.0.

**Comment by worace** [comment]
Hi there -- sorry to revive this closed issue, but I am wondering if there is any more thought around extending Z-coordinate support more broadly to other geometry types.

If I understand correctly from the [this pull request](https://github.com/bryanjos/geo/pull/99/files) it looks like these are currently handled for Points using a dedicated `Geo.PointZ`, which gets serialized to GeoJSON as `{"type": "PointZ", "coordinates" => [x,y,z]}`.

Unfortunately the `PointZ` type currently produced by the library is not valid GeoJSON -- if you put something like `{"type":"PointZ", "coordinates":[100.0,0.0,70.0]}` into a GeoJSON linting tool like [geojson.io](http://geojson.io), it will flag it as an error.

I believe in the GeoJSON spec z-coordinates should be handled on all geometries as just an optional 3rd element in the coordinate array, for example `{"type": "Point", "coordinates": [1,2,3]}`. 

I'm curious if there have been other discussions or proposals around extending all the geometry types to support optional 3rd z elements in their coordinates?

I'm not very experienced with elixir so I'm afraid I don't have great advice about the best way to model this in elixir would be -- it might require changing the coordinate types for geometries from a 2-element to a 3-element tuple or a list or something like that. In JTS for example they model it by [subclassing the Coordinate class](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Coordinate.html).

Anyway, mostly just curious if something like this is possible, or has been considered before. Thanks!

**Comment by bryanjos** [comment]
I'll have to take a deeper look. I originally intended for it to work as with coordinates can be n-tuple because not all projections are the same and there are different dimensions. 

There may need to be some rethinking on that. Maybe the workaround for now is to make it so when 3 coordinate are found, it makes it into a pointz. 

I'm just thinking out loud right now but will think some more on it and welcome any advice or feedback.

Also thanks for pointing me to geojson.io. I didn't know it existed!

**Comment by JonGretar** [comment]
Section 4 of [rfc7946](https://tools.ietf.org/html/rfc7946#section-4) has this to say about it:

>  An OPTIONAL third-position element SHALL
   be the height in meters above or below the WGS 84 reference
   ellipsoid.  In the absence of elevation values, applications
   sensitive to height or depth SHOULD interpret positions as being at
   local ground or sea level.

The problem is that this applies to all geometries. Not only `Point` geometries. So it would take some slight restructuring of Geo to support this. I'll be happy to join in and do some thinking on how it could be if supporting optional 3rd coordinate on all geometries is something you wish to do. 

I do understand that the library is a Geo library but not a GeoJSON library so if you decide not to support optional 3rd element. It's a perfectly valid choice. But even if you decide you not to support that it might be a good idea to change the GeoJSON decoder to support reading 3 element coordinates and simply thowing away the 3rd element. That would eliminate it throwing when reading valid GeoJSON files.

**Comment by JonGretar** [comment]
If you choose not to have generic support of 3 element coordinates I would recommend the JSON encoder/decoder to do the following:

Encoder:

 * `%Point{}` -> `{"type": "Point", "coordinates": [1,2]}`
 * `%PointM{}` -> `{"type": "Point", "coordinates": [1,2]}`
 * `%PointZ{}` -> `{"type": "Point", "coordinates": [1,2, 3]}`
 * `%PointZM{}` -> `{"type": "Point", "coordinates": [1,2, 3]}`

Decoder:

 * `{"type": "Point", "coordinates": [1,2]}` -> `%Point{}`
 * `{"type": "Point", "coordinates": [1,2,3]}` -> `%PointZ{}`
 * `{"type": "OtherGeometriesWith3Elements", "coordinates": [1,2,3]}` -> __discard the 3rd element__
